//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuyoTextEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuyoTextEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be larger than &apos;{1}&apos;..
        /// </summary>
        internal static string CannotBeLargerThan {
            get {
                return ResourceManager.GetString("CannotBeLargerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character &apos;{0}&apos; does not exist in the font file..
        /// </summary>
        internal static string CharacterNotFoundInFontFile {
            get {
                return ResourceManager.GetString("CharacterNotFoundInFontFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; does not have the required attribute &apos;{1}&apos;..
        /// </summary>
        internal static string ElementAttributeNotFound {
            get {
                return ResourceManager.GetString("ElementAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a font with the name &apos;{0}&apos;..
        /// </summary>
        internal static string FontNotFound {
            get {
                return ResourceManager.GetString("FontNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FNT or FPD file was used to convert this MTX file. This file must be converted without using a FNT or FPD file..
        /// </summary>
        internal static string FpdOrFntNotRequired {
            get {
                return ResourceManager.GetString("FpdOrFntNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FNT or FPD file is required to convert this MTX file..
        /// </summary>
        internal static string FpdOrFntRequired {
            get {
                return ResourceManager.GetString("FpdOrFntRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no character associated with the index &apos;{0}&apos; in the font file..
        /// </summary>
        internal static string IndexNotFoundInFontFile {
            get {
                return ResourceManager.GetString("IndexNotFoundInFontFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid CNVRS-TEXT file..
        /// </summary>
        internal static string InvalidCnvrsTextFile {
            get {
                return ResourceManager.GetString("InvalidCnvrsTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid element..
        /// </summary>
        internal static string InvalidElement {
            get {
                return ResourceManager.GetString("InvalidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid FIF file..
        /// </summary>
        internal static string InvalidFifFile {
            get {
                return ResourceManager.GetString("InvalidFifFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid FNT file. If this is a FNT file from the 3DS version of Puyo Puyo!! 20th Anniversary or from Puyo Puyo!! Quest, it should not be used to convert the MTX file..
        /// </summary>
        internal static string InvalidFntFile {
            get {
                return ResourceManager.GetString("InvalidFntFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid FPD file..
        /// </summary>
        internal static string InvalidFpdFile {
            get {
                return ResourceManager.GetString("InvalidFpdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid MTX file..
        /// </summary>
        internal static string InvalidMtxFile {
            get {
                return ResourceManager.GetString("InvalidMtxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a layout with the name &apos;{0}&apos;..
        /// </summary>
        internal static string LayoutNotFound {
            get {
                return ResourceManager.GetString("LayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a sheet with the name &apos;{0}&apos;..
        /// </summary>
        internal static string SheetNotFound {
            get {
                return ResourceManager.GetString("SheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string ValueNull {
            get {
                return ResourceManager.GetString("ValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name: {0}.
        /// </summary>
        internal static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening and ending tag mismatch..
        /// </summary>
        internal static string XmlTagMismatch {
            get {
                return ResourceManager.GetString("XmlTagMismatch", resourceCulture);
            }
        }
    }
}
